version: '3.7'

services:

  servidor:
    container_name: servidor
    build: ./Server
    environment:
      - DEBUG
    ports:
      - 6000:6500
    volumes:
      - ./Server:/Server/
    stdin_open: true
    tty: true
    command: Server/app/Server.py
    

  cliente:
    container_name: cliente
    build: ./Generic_Client
    environment:
      - DEBUG
    ports:
      - 8500:8500
    volumes:
      - ./Generic_Client:/Cliente/
    stdin_open: true
    tty: true
    command: Cliente/app/Client.py
    depends_on:
      - servidor