version: '1'

services:

  servidor:
    build: ./Server
    environment:
      - DEBUG
    ports:
      - 6000:6500
    volumes:
      - type: volume
        source: ./
        target: /data
    stdin_open: true
    tty: true
    
    """
    command: app/Headnode.py
    depends_on:
      - datanode1
    """
  cliente_1:
    build: ./client_1
    environment:
      - DEBUG
    ports:
      - 8500:8500
    volumes:
      - type: volume
        source: ./
        target: /data
    stdin_open: true
    tty: true
    command: app/Client.py
    depends_on:
      - servidor

  cliente_2:
    build: ./client_2
    environment:
      - DEBUG
    ports:
      - 8600:8600
    volumes:
      - type: volume
        source: ./
        target: /data
    stdin_open: true
    tty: true
    command: app/Client.py
    depends_on:
      - servidor      
