# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Chat_pb2 as Chat__pb2


class ChatStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Saludo = channel.unary_unary(
        '/ChatRPC.Chat/Saludo',
        request_serializer=Chat__pb2.Saludos.SerializeToString,
        response_deserializer=Chat__pb2.Saludos.FromString,
        )
    self.EnvioSolicitud = channel.unary_unary(
        '/ChatRPC.Chat/EnvioSolicitud',
        request_serializer=Chat__pb2.MensajeCliente.SerializeToString,
        response_deserializer=Chat__pb2.Confirmacion.FromString,
        )
    self.DespachoMensajes = channel.unary_stream(
        '/ChatRPC.Chat/DespachoMensajes',
        request_serializer=Chat__pb2.Consulta.SerializeToString,
        response_deserializer=Chat__pb2.MensajeCliente.FromString,
        )


class ChatServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Saludo(self, request, context):
    """


    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EnvioSolicitud(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DespachoMensajes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Saludo': grpc.unary_unary_rpc_method_handler(
          servicer.Saludo,
          request_deserializer=Chat__pb2.Saludos.FromString,
          response_serializer=Chat__pb2.Saludos.SerializeToString,
      ),
      'EnvioSolicitud': grpc.unary_unary_rpc_method_handler(
          servicer.EnvioSolicitud,
          request_deserializer=Chat__pb2.MensajeCliente.FromString,
          response_serializer=Chat__pb2.Confirmacion.SerializeToString,
      ),
      'DespachoMensajes': grpc.unary_stream_rpc_method_handler(
          servicer.DespachoMensajes,
          request_deserializer=Chat__pb2.Consulta.FromString,
          response_serializer=Chat__pb2.MensajeCliente.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ChatRPC.Chat', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
