# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Chat.proto',
  package='ChatRPC',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nChat.proto\x12\x07\x43hatRPC\"M\n\x07Saludos\x12\x0c\n\x04Tipo\x18\x01 \x01(\x05\x12\x11\n\tIdCliente\x18\x02 \x01(\t\x12\x12\n\nIdServidor\x18\x03 \x01(\t\x12\r\n\x05\x45rror\x18\x04 \x01(\t\"r\n\x0eMensajeCliente\x12\x15\n\rIdPropietario\x18\x01 \x01(\t\x12\x16\n\x0eIdDestinatario\x18\x02 \x01(\t\x12\x11\n\tIdMensaje\x18\x03 \x01(\t\x12\x0f\n\x07Mensaje\x18\x04 \x01(\t\x12\r\n\x05\x45rror\x18\x05 \x01(\t\"\x1d\n\x08\x43onsulta\x12\x11\n\tIdCliente\x18\x01 \x01(\t\"U\n\x0c\x43onfirmacion\x12\x0c\n\x04Tipo\x18\x01 \x01(\x05\x12\x15\n\rIdPropietario\x18\x02 \x01(\t\x12\x11\n\tIdMensaje\x18\x03 \x01(\t\x12\r\n\x05\x45rror\x18\x04 \x01(\t2\xb8\x01\n\x04\x43hat\x12,\n\x06Saludo\x12\x10.ChatRPC.Saludos\x1a\x10.ChatRPC.Saludos\x12@\n\x0e\x45nvioSolicitud\x12\x17.ChatRPC.MensajeCliente\x1a\x15.ChatRPC.Confirmacion\x12@\n\x10\x44\x65spachoMensajes\x12\x11.ChatRPC.Consulta\x1a\x17.ChatRPC.MensajeCliente0\x01\x62\x06proto3')
)




_SALUDOS = _descriptor.Descriptor(
  name='Saludos',
  full_name='ChatRPC.Saludos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Tipo', full_name='ChatRPC.Saludos.Tipo', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IdCliente', full_name='ChatRPC.Saludos.IdCliente', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IdServidor', full_name='ChatRPC.Saludos.IdServidor', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Error', full_name='ChatRPC.Saludos.Error', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=100,
)


_MENSAJECLIENTE = _descriptor.Descriptor(
  name='MensajeCliente',
  full_name='ChatRPC.MensajeCliente',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IdPropietario', full_name='ChatRPC.MensajeCliente.IdPropietario', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IdDestinatario', full_name='ChatRPC.MensajeCliente.IdDestinatario', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IdMensaje', full_name='ChatRPC.MensajeCliente.IdMensaje', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Mensaje', full_name='ChatRPC.MensajeCliente.Mensaje', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Error', full_name='ChatRPC.MensajeCliente.Error', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=216,
)


_CONSULTA = _descriptor.Descriptor(
  name='Consulta',
  full_name='ChatRPC.Consulta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IdCliente', full_name='ChatRPC.Consulta.IdCliente', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=247,
)


_CONFIRMACION = _descriptor.Descriptor(
  name='Confirmacion',
  full_name='ChatRPC.Confirmacion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Tipo', full_name='ChatRPC.Confirmacion.Tipo', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IdPropietario', full_name='ChatRPC.Confirmacion.IdPropietario', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IdMensaje', full_name='ChatRPC.Confirmacion.IdMensaje', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Error', full_name='ChatRPC.Confirmacion.Error', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=334,
)

DESCRIPTOR.message_types_by_name['Saludos'] = _SALUDOS
DESCRIPTOR.message_types_by_name['MensajeCliente'] = _MENSAJECLIENTE
DESCRIPTOR.message_types_by_name['Consulta'] = _CONSULTA
DESCRIPTOR.message_types_by_name['Confirmacion'] = _CONFIRMACION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Saludos = _reflection.GeneratedProtocolMessageType('Saludos', (_message.Message,), {
  'DESCRIPTOR' : _SALUDOS,
  '__module__' : 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:ChatRPC.Saludos)
  })
_sym_db.RegisterMessage(Saludos)

MensajeCliente = _reflection.GeneratedProtocolMessageType('MensajeCliente', (_message.Message,), {
  'DESCRIPTOR' : _MENSAJECLIENTE,
  '__module__' : 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:ChatRPC.MensajeCliente)
  })
_sym_db.RegisterMessage(MensajeCliente)

Consulta = _reflection.GeneratedProtocolMessageType('Consulta', (_message.Message,), {
  'DESCRIPTOR' : _CONSULTA,
  '__module__' : 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:ChatRPC.Consulta)
  })
_sym_db.RegisterMessage(Consulta)

Confirmacion = _reflection.GeneratedProtocolMessageType('Confirmacion', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMACION,
  '__module__' : 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:ChatRPC.Confirmacion)
  })
_sym_db.RegisterMessage(Confirmacion)



_CHAT = _descriptor.ServiceDescriptor(
  name='Chat',
  full_name='ChatRPC.Chat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=337,
  serialized_end=521,
  methods=[
  _descriptor.MethodDescriptor(
    name='Saludo',
    full_name='ChatRPC.Chat.Saludo',
    index=0,
    containing_service=None,
    input_type=_SALUDOS,
    output_type=_SALUDOS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EnvioSolicitud',
    full_name='ChatRPC.Chat.EnvioSolicitud',
    index=1,
    containing_service=None,
    input_type=_MENSAJECLIENTE,
    output_type=_CONFIRMACION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DespachoMensajes',
    full_name='ChatRPC.Chat.DespachoMensajes',
    index=2,
    containing_service=None,
    input_type=_CONSULTA,
    output_type=_MENSAJECLIENTE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAT)

DESCRIPTOR.services_by_name['Chat'] = _CHAT

# @@protoc_insertion_point(module_scope)
