version: '3.7'
services:
  servidor:
    build: ./Server
    environment:
      - DEBUG
    network_mode: host    
    expose: 
      - 4369
      - 5671
      - 5672
      - 25672
    volumes:
      - ./Server:/Server/
    stdin_open: true
    tty: true
    command: bash -c "sudo service rabbitmq-server start && python3 Server/app/servidor.py"
    
  cliente:
    build: ./Client
    environment:
      - DEBUG
    network_mode: host
    expose:
      - 4369
      - 5671
      - 5672
      - 25672
    volumes:
      - ./Client:/Cliente/
    stdin_open: true
    tty: true
    command: bash -c "sleep 10 && python3 Cliente/app/cliente.py"
    depends_on: 
      - servidor
