version: '2'

services:

  cliente:
    build: ./node
    environment:
      - DEBUG
    network_mode: host
    ports:
      - 5500:5500
    volumes:
      - .:/srv
    stdin_open: true
    tty: true
    command: app/Client.py
    depends_on:
      - "servidor"

  servidor:
    build: ./node
    environment:
      - DEBUG
    ports:
      - 5500:5500
    volumes:
      - .:/srv
    command: app/Headnode.py
    stdin_open: true
    tty: true
    depends_on:
      - "datanode"

  datanode:
    build: ./node
    environment:
      - DEBUG
    ports:
      - 8000:8000
    volumes:
      - .:/srv
    stdin_open: true
    tty: true
    command: app/Datanode.py


  
